version: '3.7'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'mssqldb'
    environment:
      SA_PASSWORD: '022020_sQ'
      ACCEPT_EULA: 'Y'
    ports:
      - '1401:1433'
    volumes:
      - ./docker-volumes/db/mssql/data:/var/opt/mssql/data
      - ./docker-volumes/db/mssql/log:/var/opt/mssql/log
      - ./docker-volumes/db/mssql/secrets:/var/opt/mssql/secrets

  mongo:
    image: mongo
    container_name: 'mongodb'
    environment:
      MONGO_DATA_DIR: '/data/db'
      MONGO_LOG_DIR: '/dev/null'
      MONGO_INITDB_DATABASE: 'watcher-data-storage'
    ports:
      - '27017:27017'
    # volumes:
    #   - ./docker-volumes/db/mongo:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    # volumes:
    #   - ./docker-volumes/rabbitmq:/var/lib/rabbitmq

  core-api:
    container_name: watcher-core-api
    build: 
      context: .
      dockerfile: Core.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
    ports:
      - 8090:80
    depends_on:
      - mssql
      - mongo
      - rabbitmq

  data-accumulator-api:
    container_name: watcher-data-accumulator-api
    build: 
      context: .
      dockerfile: DataAccumulator.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      # - ASPNETCORE_URLS=https://+;http://+
      # - ASPNETCORE_HTTPS_PORT=44392
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/watcher-core.pfx
      # - ASPNETCORE_Kestrel__Certificates__Default__Password='password'
    ports:
      - '59404:80'
      # - '44392:44392'
    depends_on:
      - mongo
      - rabbitmq
    # volumes:
      # - %USERPROFILE%\.aspnet\https:/https/

  web-client:
    hostname: watcher.loc.com
    container_name: watcher-web-client
    build: 
      context: .
      dockerfile: WebClient.Dockerfile
    ports:
      - '8110:80'
    depends_on:
      - core-api