version: '3.7'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: 'mssqldb'
    environment:
      SA_PASSWORD: '12344321'
      ACCEPT_EULA: 'Y'
    ports:
      - '1401:1433'

  mongo:
    image: mongo
    container_name: 'mongodb'
    environment:
      MONGO_DATA_DIR: '/data/db'
      MONGO_LOG_DIR: '/dev/null'
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    hostname: rabbitmq
    environment:
      # RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    # volumes:
    #   - ./docker/rabbitmq:/var/lib/rabbitmq

  core-api:
    container_name: watcher-core-api
    build: 
      context: .
      dockerfile: Core.Dockerfile
    ports:
      - 8090:80
    depends_on:
      - mssql
      - mongo
      - rabbitmq

  data-accumulator-api:
    container_name: watcher-data-accumulator-api
    build: 
      context: .
      dockerfile: DataAccumulator.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:44392;http://+:80
      - ASPNETCORE_HTTPS_PORT=44392
    ports:
      - "59404:80"
      - "44392:44392"
    depends_on:
      - mongo
      - rabbitmq

  web-client:
    hostname: watcher.loc.com
    container_name: watcher-web-client
    build: 
      context: .
      dockerfile: WebClient.Dockerfile
    ports:
      - "8110:80"
    depends_on:
      - core-api